# Generated by Django 6.0.3 on 2026-04-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('Haircut & Style', 'Haircut & Style'), ('Balayage', 'Balayage'), ('Keratin', 'Keratin'), ('Facial', 'Facial'), ('Spa Massage', 'Spa Massage')], max_length=100),
        ),
    ]
